using UnityEngine;

public class RefBlackJack_ReferenceApplier : MonoBehaviour,IApplier {
	public void SetReference()
	{
		RefBlackJack mRefBlackJack = gameObject.GetComponent<RefBlackJack>();
		if(mRefBlackJack.PnlMain == null) mRefBlackJack.PnlMain = mRefBlackJack.transform.gameObject;
		if(mRefBlackJack.BoardWord == null) mRefBlackJack.BoardWord = mRefBlackJack.transform.Find("SkeletonGraphic (BJ_RuleTextFX)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.LstPlayerLight[0] == null) mRefBlackJack.LstPlayerLight[0] = mRefBlackJack.transform.Find("Gobj_BackLightBox/Ani_BGL (0)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.LstPlayerLight[1] == null) mRefBlackJack.LstPlayerLight[1] = mRefBlackJack.transform.Find("Gobj_BackLightBox/Ani_BGL (1)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.LstPlayerLight[2] == null) mRefBlackJack.LstPlayerLight[2] = mRefBlackJack.transform.Find("Gobj_BackLightBox/Ani_BGL (2)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.LstPlayerLight[3] == null) mRefBlackJack.LstPlayerLight[3] = mRefBlackJack.transform.Find("Gobj_BackLightBox/Ani_BGL (3)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.LstPlayerLight[4] == null) mRefBlackJack.LstPlayerLight[4] = mRefBlackJack.transform.Find("Gobj_BackLightBox/Ani_BGL (4)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.LstBtnSeat[0] == null) mRefBlackJack.LstBtnSeat[0] = mRefBlackJack.transform.Find("Gobj_ChooseSeat/UIBtn_Seat (0)").gameObject;
		if(mRefBlackJack.LstBtnSeat[1] == null) mRefBlackJack.LstBtnSeat[1] = mRefBlackJack.transform.Find("Gobj_ChooseSeat/UIBtn_Seat (1)").gameObject;
		if(mRefBlackJack.LstBtnSeat[2] == null) mRefBlackJack.LstBtnSeat[2] = mRefBlackJack.transform.Find("Gobj_ChooseSeat/UIBtn_Seat (2)").gameObject;
		if(mRefBlackJack.LstBtnSeat[3] == null) mRefBlackJack.LstBtnSeat[3] = mRefBlackJack.transform.Find("Gobj_ChooseSeat/UIBtn_Seat (3)").gameObject;
		if(mRefBlackJack.LstBtnSeat[4] == null) mRefBlackJack.LstBtnSeat[4] = mRefBlackJack.transform.Find("Gobj_ChooseSeat/UIBtn_Seat (4)").gameObject;
		if(mRefBlackJack.LstDealCard[0] == null) mRefBlackJack.LstDealCard[0] = mRefBlackJack.transform.Find("Gobj_DealCardBox/UIImg_DealCard (0)").gameObject;
		if(mRefBlackJack.LstDealCard[1] == null) mRefBlackJack.LstDealCard[1] = mRefBlackJack.transform.Find("Gobj_DealCardBox/UIImg_DealCard (1)").gameObject;
		if(mRefBlackJack.LstDealCard[2] == null) mRefBlackJack.LstDealCard[2] = mRefBlackJack.transform.Find("Gobj_DealCardBox/UIImg_DealCard (2)").gameObject;
		if(mRefBlackJack.LstDealCard[3] == null) mRefBlackJack.LstDealCard[3] = mRefBlackJack.transform.Find("Gobj_DealCardBox/UIImg_DealCard (3)").gameObject;
		if(mRefBlackJack.LstDealCard[4] == null) mRefBlackJack.LstDealCard[4] = mRefBlackJack.transform.Find("Gobj_DealCardBox/UIImg_DealCard (4)").gameObject;
		if(mRefBlackJack.AniHand[0] == null) mRefBlackJack.AniHand[0] = mRefBlackJack.transform.Find("Gobj_HandAni/Ani_Hand (0)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHand[1] == null) mRefBlackJack.AniHand[1] = mRefBlackJack.transform.Find("Gobj_HandAni/Ani_Hand (1)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHand[2] == null) mRefBlackJack.AniHand[2] = mRefBlackJack.transform.Find("Gobj_HandAni/Ani_Hand (2)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHand[3] == null) mRefBlackJack.AniHand[3] = mRefBlackJack.transform.Find("Gobj_HandAni/Ani_Hand (3)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHand[4] == null) mRefBlackJack.AniHand[4] = mRefBlackJack.transform.Find("Gobj_HandAni/Ani_Hand (4)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHand[5] == null) mRefBlackJack.AniHand[5] = mRefBlackJack.transform.Find("Gobj_HandAni/Ani_Hand (5)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHand[6] == null) mRefBlackJack.AniHand[6] = mRefBlackJack.transform.Find("Gobj_HandAni/Ani_Hand (6)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHandLight[0] == null) mRefBlackJack.AniHandLight[0] = mRefBlackJack.transform.Find("Gobj_HandLightAni/Ani_HandLight (0)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHandLight[1] == null) mRefBlackJack.AniHandLight[1] = mRefBlackJack.transform.Find("Gobj_HandLightAni/Ani_HandLight (1)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHandLight[2] == null) mRefBlackJack.AniHandLight[2] = mRefBlackJack.transform.Find("Gobj_HandLightAni/Ani_HandLight (2)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHandLight[3] == null) mRefBlackJack.AniHandLight[3] = mRefBlackJack.transform.Find("Gobj_HandLightAni/Ani_HandLight (3)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHandLight[4] == null) mRefBlackJack.AniHandLight[4] = mRefBlackJack.transform.Find("Gobj_HandLightAni/Ani_HandLight (4)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHandLight[5] == null) mRefBlackJack.AniHandLight[5] = mRefBlackJack.transform.Find("Gobj_HandLightAni/Ani_HandLight (5)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.AniHandLight[6] == null) mRefBlackJack.AniHandLight[6] = mRefBlackJack.transform.Find("Gobj_HandLightAni/Ani_HandLight (6)").GetComponent<Spine.Unity.SkeletonGraphic>();
		if(mRefBlackJack.BtnPreAction == null) mRefBlackJack.BtnPreAction = mRefBlackJack.transform.Find("Gobj_PreAction/UIBtn_PreAction").gameObject;
		if(mRefBlackJack.xSetBet.View == null) mRefBlackJack.xSetBet.View = mRefBlackJack.transform.Find("Gobj_SetBetBox").gameObject;
		if(mRefBlackJack.xSetBet.BtnDouble == null) mRefBlackJack.xSetBet.BtnDouble = mRefBlackJack.transform.Find("Gobj_SetBetBox/UIBtn_Double").gameObject;
		if(mRefBlackJack.xSetBet.BtnRepeat == null) mRefBlackJack.xSetBet.BtnRepeat = mRefBlackJack.transform.Find("Gobj_SetBetBox/UIBtn_Repeat").gameObject;
		if(mRefBlackJack.xSetBet.BtnUndo == null) mRefBlackJack.xSetBet.BtnUndo = mRefBlackJack.transform.Find("Gobj_SetBetBox/UIBtn_Undo").gameObject;
		if(mRefBlackJack.xSetBet.BtnDeal == null) mRefBlackJack.xSetBet.BtnDeal = mRefBlackJack.transform.Find("Gobj_SetBetBox/UIBtn_Deal").gameObject;
		if(mRefBlackJack.xSetBet.LstBtnClip[0] == null) mRefBlackJack.xSetBet.LstBtnClip[0] = mRefBlackJack.transform.Find("Gobj_SetBetBox/Gobj_BetBox/UIBtn_0").gameObject;
		if(mRefBlackJack.xSetBet.LstBtnClip[1] == null) mRefBlackJack.xSetBet.LstBtnClip[1] = mRefBlackJack.transform.Find("Gobj_SetBetBox/Gobj_BetBox/UIBtn_1").gameObject;
		if(mRefBlackJack.xSetBet.LstBtnClip[2] == null) mRefBlackJack.xSetBet.LstBtnClip[2] = mRefBlackJack.transform.Find("Gobj_SetBetBox/Gobj_BetBox/UIBtn_2").gameObject;
		if(mRefBlackJack.xSetBet.LstBtnClip[3] == null) mRefBlackJack.xSetBet.LstBtnClip[3] = mRefBlackJack.transform.Find("Gobj_SetBetBox/Gobj_BetBox/UIBtn_3").gameObject;
		if(mRefBlackJack.xSetBet.LstBtnClip[4] == null) mRefBlackJack.xSetBet.LstBtnClip[4] = mRefBlackJack.transform.Find("Gobj_SetBetBox/Gobj_BetBox/UIBtn_4").gameObject;
		if(mRefBlackJack.xSetBet.LstBtnClip[5] == null) mRefBlackJack.xSetBet.LstBtnClip[5] = mRefBlackJack.transform.Find("Gobj_SetBetBox/Gobj_BetBox/UIBtn_5").gameObject;
		if(mRefBlackJack.xSetBet.Title == null) mRefBlackJack.xSetBet.Title = mRefBlackJack.transform.Find("Gobj_SetBetBox/UITxt_Msg").GetComponent<UnityEngine.UI.Text>();
		if(mRefBlackJack.xSetBet.Counter == null) mRefBlackJack.xSetBet.Counter = mRefBlackJack.transform.Find("Gobj_SetBetBox/Gobj_CountdownBox/UIImg_Count").GetComponent<AnimationCoin>();
		if(mRefBlackJack.xDecision.View == null) mRefBlackJack.xDecision.View = mRefBlackJack.transform.Find("Gobj_DecideBox").gameObject;
		if(mRefBlackJack.xDecision.BtnSplit == null) mRefBlackJack.xDecision.BtnSplit = mRefBlackJack.transform.Find("Gobj_DecideBox/UIBtn_Split").gameObject;
		if(mRefBlackJack.xDecision.BtnStand == null) mRefBlackJack.xDecision.BtnStand = mRefBlackJack.transform.Find("Gobj_DecideBox/UIBtn_Stand").gameObject;
		if(mRefBlackJack.xDecision.BtnHit == null) mRefBlackJack.xDecision.BtnHit = mRefBlackJack.transform.Find("Gobj_DecideBox/UIBtn_Hit").gameObject;
		if(mRefBlackJack.xDecision.BtnDouble == null) mRefBlackJack.xDecision.BtnDouble = mRefBlackJack.transform.Find("Gobj_DecideBox/UIBtn_Double").gameObject;
		if(mRefBlackJack.xDecision.Title == null) mRefBlackJack.xDecision.Title = mRefBlackJack.transform.Find("Gobj_DecideBox/UITxt_Msg").GetComponent<UnityEngine.UI.Text>();
		if(mRefBlackJack.xDecision.Counter == null) mRefBlackJack.xDecision.Counter = mRefBlackJack.transform.Find("Gobj_DecideBox/Gobj_CountdownBox/UIImg_Count").GetComponent<AnimationCoin>();
		if(mRefBlackJack.xInsurance.View == null) mRefBlackJack.xInsurance.View = mRefBlackJack.transform.Find("Gobj_InsuranceBox").gameObject;
		if(mRefBlackJack.xInsurance.BtnYes == null) mRefBlackJack.xInsurance.BtnYes = mRefBlackJack.transform.Find("Gobj_InsuranceBox/UIBtn_Yes").gameObject;
		if(mRefBlackJack.xInsurance.BtnNo == null) mRefBlackJack.xInsurance.BtnNo = mRefBlackJack.transform.Find("Gobj_InsuranceBox/UIBtn_No").gameObject;
		if(mRefBlackJack.xInsurance.Counter == null) mRefBlackJack.xInsurance.Counter = mRefBlackJack.transform.Find("Gobj_InsuranceBox/Gobj_CountdownBox/UIImg_Count").GetComponent<AnimationCoin>();
		if(mRefBlackJack.xStatus.View == null) mRefBlackJack.xStatus.View = mRefBlackJack.transform.Find("Gobj_StatusBox").gameObject;
		if(mRefBlackJack.xStatus.Status == null) mRefBlackJack.xStatus.Status = mRefBlackJack.transform.Find("Gobj_StatusBox/UITxt_Msg").GetComponent<UnityEngine.UI.Text>();
		if(mRefBlackJack.xWin.View == null) mRefBlackJack.xWin.View = mRefBlackJack.transform.Find("Gobj_WinBox").gameObject;
		if(mRefBlackJack.xWin.Coin == null) mRefBlackJack.xWin.Coin = mRefBlackJack.transform.Find("Gobj_WinBox/Gobj_Coin/UITxt").GetComponent<AnimationCoin>();
		if(mRefBlackJack.PlayerData[0].View == null) mRefBlackJack.PlayerData[0].View = mRefBlackJack.transform.Find("Gobj_PlayerData (0)").gameObject;
		if(mRefBlackJack.PlayerData[1].View == null) mRefBlackJack.PlayerData[1].View = mRefBlackJack.transform.Find("Gobj_PlayerData (1)").gameObject;
		if(mRefBlackJack.PlayerData[2].View == null) mRefBlackJack.PlayerData[2].View = mRefBlackJack.transform.Find("Gobj_PlayerData (2)").gameObject;
		if(mRefBlackJack.PlayerData[3].View == null) mRefBlackJack.PlayerData[3].View = mRefBlackJack.transform.Find("Gobj_PlayerData (3)").gameObject;
		if(mRefBlackJack.PlayerData[4].View == null) mRefBlackJack.PlayerData[4].View = mRefBlackJack.transform.Find("Gobj_PlayerData (4)").gameObject;
		if(mRefBlackJack.SmapleLeaderCard == null) mRefBlackJack.SmapleLeaderCard = mRefBlackJack.transform.Find("Gobj_LeaderCard/Gobj_CardBox/Gobj_Card (0)").gameObject;
		if(mRefBlackJack.LeaderPoint == null) mRefBlackJack.LeaderPoint = mRefBlackJack.transform.Find("Gobj_LeaderCard/Gobj_Point").gameObject;
		if(mRefBlackJack.OperatorMask == null) mRefBlackJack.OperatorMask = mRefBlackJack.transform.Find("Gobj_Mask").gameObject;
	}
}